name: Harvester Bot Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Fetch Git tags
      run: git fetch --tags
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: github-bot
        dockerfile: github-bot/
        repo: rancherlabs/harvester-github-bot
        tag: ${{ github.ref }}
        build-args: |
          ARCH=amd64